import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import { Auth } from 'ui/Auth';
import { Mesh } from 'ui/Mesh';
import styles from '../styles/Home.module.css';

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex h-full w-full flex-col items-center justify-center">
        <h1 className={'mb-5 text-3xl text-white'}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>
        <Auth />
      </main>
    </>
  );
};

export default Home;
